# Generated by Django 2.1 on 2018-11-03 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '__first__'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HungarianAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('city', models.TextField(help_text='The type of munacipility e.g. city, village, etc', verbose_name='city')),
                ('street_name', models.TextField(verbose_name='street name')),
                ('street_type', models.TextField(verbose_name='street type')),
                ('house_number', models.TextField(verbose_name='house number')),
                ('postal_code', models.TextField(verbose_name='recipient')),
                ('country', models.TextField(verbose_name='country')),
            ],
            options={
                'verbose_name': 'Hungarian address',
                'verbose_name_plural': 'Hungarian addresses',
            },
        ),
        migrations.CreateModel(
            name='JapaneseAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('building', models.TextField(help_text='The name of the building', verbose_name='building')),
                ('apartment', models.TextField(help_text='Room number', verbose_name='apartment')),
                ('chome', models.TextField(help_text='The first number in the triplet ◯町目◯番◯号', verbose_name='chome')),
                ('ban', models.TextField(help_text='The second number in the triplet ◯町目◯番◯号', verbose_name='ban')),
                ('go', models.TextField(help_text='The third number in the triplet ◯町目◯番◯号', verbose_name='go')),
                ('ward', models.TextField(help_text='Ward or island', verbose_name='ward')),
                ('city', models.TextField(verbose_name='city')),
                ('prefecture', models.TextField(verbose_name='prefecture')),
                ('postal_code', models.TextField(verbose_name='postal code')),
                ('country', models.TextField(verbose_name='country')),
                ('p_o_box', models.TextField(verbose_name='P.O. box')),
            ],
            options={
                'verbose_name': 'Japanese address',
                'verbose_name_plural': 'Japanese addresses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='descrition')),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='image1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='image1')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='image1')),
                ('image4', models.ImageField(blank=True, upload_to='', verbose_name='image1')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('remaining_quantity', models.IntegerField(verbose_name='remaining quantity')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Campaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_quantity', models.IntegerField(verbose_name='product quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('currency', models.CharField(choices=[('HUF', 'Hungarian Forint'), ('USD', 'US Dollar'), ('JPY', 'Japanese Yen')], default='HUF', max_length=3, verbose_name='currency')),
                ('price', models.IntegerField(verbose_name='price')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Product price',
                'verbose_name_plural': 'Product price',
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('remaining_quantity', models.IntegerField(verbose_name='remaining quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('in_stock', models.CharField(choices=[('IS', 'In Stock'), ('OOS', 'Out of Stock')], default='IS', max_length=3, verbose_name='in stock')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Product status',
                'verbose_name_plural': 'Product status',
            },
        ),
        migrations.CreateModel(
            name='ProductStorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Product storage location',
                'verbose_name_plural': 'Product storage locations',
            },
        ),
        migrations.AddField(
            model_name='productstatus',
            name='product_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductStorageLocation'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='japaneseaddress',
            name='storage_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_address', to='product.ProductStorageLocation'),
        ),
        migrations.AddField(
            model_name='hungarianaddress',
            name='storage_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hungarian_address', to='product.ProductStorageLocation'),
        ),
        migrations.AlterUniqueTogether(
            name='productstatus',
            unique_together={('product', 'product_location')},
        ),
        migrations.AlterUniqueTogether(
            name='productsale',
            unique_together={('product', 'sale')},
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together={('product', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='productcampaign',
            unique_together={('product', 'campaign')},
        ),
    ]
