# Generated by Django 2.1 on 2018-11-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hungarianaddress',
            name='storage_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hungarian_address', to='product.ProductStorageLocation', verbose_name='storage_location'),
        ),
        migrations.AlterField(
            model_name='japaneseaddress',
            name='storage_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_address', to='product.ProductStorageLocation', verbose_name='storage_location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image4'),
        ),
        migrations.AlterField(
            model_name='productcampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Campaign', verbose_name='campaign'),
        ),
        migrations.AlterField(
            model_name='productcampaign',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Sale', verbose_name='sale'),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='product_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductStorageLocation', verbose_name='product_location'),
        ),
    ]
