export const PRODUCT_BY_CATEGORY_LOAD_START = 'PRODUCT_BY_CATEGORY_LOAD_START';
export const PRODUCT_BY_CATEGORY_LOAD_FAILED = 'PRODUCT_BY_CATEGORY_LOAD_FAILED';
export const PRODUCT_BY_CATEGORY_LOAD_SUCCEEDED = 'PRODUCT_BY_CATEGORY_LOAD_SUCCEEDED';
