# Generated by Django 2.1 on 2018-11-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='campaign_products', through='product.ProductCampaign', to='product.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='sale_products', through='product.ProductSale', to='product.Product'),
        ),
    ]
