# Generated by Django 2.1 on 2018-11-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hungarian_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_hu_adr', to='product.HungarianAddress'),
        ),
        migrations.AddField(
            model_name='user',
            name='hungarian_billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_hu_bill_adr', to='product.HungarianAddress'),
        ),
        migrations.AddField(
            model_name='user',
            name='japanese_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_jp_adr', to='product.JapaneseAddress'),
        ),
        migrations.AddField(
            model_name='user',
            name='japanese_billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_jp_bill_adr', to='product.JapaneseAddress'),
        ),
    ]
